require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'HammerApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'HammerAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper' => '0.79.1' }) # update this part
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'HammerApp-tvOS' do
  # Pods for HammerApp-tvOS

  target 'HammerApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
